# Site settings
title: Price Clark Personal Site 
email: gpwclark@gmail.com
description: > # this means to ignore newlines until "baseurl:"
      This is my personal site/blog/resume.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://gpwclark.github.io" # the base hostname & protocol for your site
github_username: gpwclark 
# Build settings
kramdown:                                                                                                    
  input: GFM
url: "http://gpwclark.net"
