# Site settings
title: Price Clark Personal Site 
email: gpwclark@gmail.com
description: > # this means to ignore newlines until "baseurl:"
      This is my personal site/blog/resume.
baseurl: "/_site" # the subpath of your site, e.g. /blog/
url: "http://uofantarctica.com" # the base hostname & protocol for your site
github_username: gpwclark 
# Build settings
kramdown:                                                                                                    
  input: GFM
